version: "3.9"

services:
  detect-grid-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: detect-grid-api
    ports:
      - "5000:5000" # Expose le port 5000
    environment:
      # Variables d'environnement pour la configuration en production
      FLASK_ENV: production
      FLASK_DEBUG: 0
    command: gunicorn --bind 0.0.0.0:5000 main:app



 